config/routes.rb
Rails.application.routes.draw do
  resources :booking_states
  resources :bookings
  resources :users
  resources :books
  resources :contactos
  match "/static_pages/books" => "static_pages#books", :via => :get
  match "/static_pages/help" => "static_pages#help", :via => :get
  match "/static_pages/about" => "static_pages#about", :via => :get
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/booking_state.rb
class BookingState < ApplicationRecord
end

app/models/contacto.rb
class Contacto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def index
  end
end

app/controllers/booking_states_controller.rb
class BookingStatesController < ApplicationController
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/booking_states_helper.rb
module BookingStatesHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book/index.html.erb
<h1>Book#index</h1>
<p>Find me in app/views/book/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Abril</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last nam</th>
      <th>Dni</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Password</th>
      <th>Rol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.dni %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.rol %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>